### ISSUE TITLE
Supports only nets with addresses 192.168.1.1-255

### ISSUE THREAD

**Issue by tigertv** [shayanizii/pyFindMac#1]
Supports only nets with addresses 192.168.1.1-255

https://github.com/shayanizii/pyFindMac/blob/ba329257278613c77122e683afbe701738070567/scanerRouter.py#L7

I suppose you have to give a user a chance to select current subnet of localhost, or even better define current subnet of the localhost automaticaly.

**Comment by richard-adlava** [comment]
@tigertv iv'e forked this repo https://github.com/richard-adlava/pyFindMac until the developer has pushed the new code.

**Comment by tigertv** [comment]
@richard-adlava : for what?

**Comment by tigertv** [comment]
@richard-adlava : Propose your pull request for the repo.
